# SPDX-FileCopyrightText: The openTCS Authors
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["*.woff2"]
precedence = "closest"
SPDX-FileCopyrightText = "2020 The Open Sans Project Authors (https://github.com/googlefonts/opensans)"
SPDX-License-Identifier = "OFL-1.1"
