# SPDX-FileCopyrightText: The openTCS Authors
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["*.woff2"]
precedence = "closest"
SPDX-FileCopyrightText = "2018 The Noto Project Authors (github.com/googlei18n/noto-fonts)"
SPDX-License-Identifier = "OFL-1.1"
